// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

Future<MediaMeta> readMetadata({required String path}) =>
    RustLib.instance.api.crateApiReadMetadata(path: path);

class MediaMeta {
  final String mimeType;
  final int? width;
  final int? height;
  final PlatformInt64? capturedAtMs;
  final String? cameraMake;
  final String? cameraModel;
  final double? latitude;
  final double? longitude;
  final double? altitude;
  final BigInt? durationMs;

  const MediaMeta({
    required this.mimeType,
    this.width,
    this.height,
    this.capturedAtMs,
    this.cameraMake,
    this.cameraModel,
    this.latitude,
    this.longitude,
    this.altitude,
    this.durationMs,
  });

  @override
  int get hashCode =>
      mimeType.hashCode ^
      width.hashCode ^
      height.hashCode ^
      capturedAtMs.hashCode ^
      cameraMake.hashCode ^
      cameraModel.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      altitude.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaMeta &&
          runtimeType == other.runtimeType &&
          mimeType == other.mimeType &&
          width == other.width &&
          height == other.height &&
          capturedAtMs == other.capturedAtMs &&
          cameraMake == other.cameraMake &&
          cameraModel == other.cameraModel &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          altitude == other.altitude &&
          durationMs == other.durationMs;
}
