// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

Future<MediaMeta> readMetadata({required String path}) =>
    RustLib.instance.api.crateApiReadMetadata(path: path);

/// Extract a thumbnail from a video file, returning raw JPEG/PNG bytes.
///
/// For MP4 and MOV files, reads the embedded cover-art image from the file's
/// `covr` iTunes atom without decoding any video frames. `time_ms` is accepted
/// for API compatibility but has no effect in this implementation — the `covr`
/// atom is a single fixed image independent of playback position.
///
/// If `save_path` is provided the bytes are also written to that path
/// (parent directories are created automatically).
///
/// Returns an error if no embedded thumbnail is present or the format is
/// unsupported.
Future<Uint8List> extractVideoThumbnail(
        {required String path, BigInt? timeMs, String? savePath}) =>
    RustLib.instance.api.crateApiExtractVideoThumbnail(
        path: path, timeMs: timeMs, savePath: savePath);

/// Read metadata from multiple files in parallel using Rayon.
/// Each entry is `None` if the file is unsupported or corrupt.
Future<List<MediaMeta?>> readMetadataBatch({required List<String> paths}) =>
    RustLib.instance.api.crateApiReadMetadataBatch(paths: paths);

class MediaMeta {
  final String mimeType;
  final int? width;
  final int? height;
  final PlatformInt64? capturedAtMs;
  final PlatformInt64? modifiedAtMs;
  final String? cameraMake;
  final String? cameraModel;
  final double? latitude;
  final double? longitude;
  final double? altitude;
  final BigInt? durationMs;

  const MediaMeta({
    required this.mimeType,
    this.width,
    this.height,
    this.capturedAtMs,
    this.modifiedAtMs,
    this.cameraMake,
    this.cameraModel,
    this.latitude,
    this.longitude,
    this.altitude,
    this.durationMs,
  });

  @override
  int get hashCode =>
      mimeType.hashCode ^
      width.hashCode ^
      height.hashCode ^
      capturedAtMs.hashCode ^
      modifiedAtMs.hashCode ^
      cameraMake.hashCode ^
      cameraModel.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      altitude.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaMeta &&
          runtimeType == other.runtimeType &&
          mimeType == other.mimeType &&
          width == other.width &&
          height == other.height &&
          capturedAtMs == other.capturedAtMs &&
          modifiedAtMs == other.modifiedAtMs &&
          cameraMake == other.cameraMake &&
          cameraModel == other.cameraModel &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          altitude == other.altitude &&
          durationMs == other.durationMs;
}
